### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Senwang98** [haoyuc/A2N#1]
Hi, @haoyuc 
Thanks for your work
For the convenience of comparison, can you share the pre-trained model or benchmark results.
Looking for you work and good luck!

**Comment by haoyuc** [comment]
Hi, thank you for your suggestion! 
I have uploaded the visual results, you can download them at Google Drive or Baidu Netdisk. 
As for the training and testing codes, I will update them as soon as I finish cleaning the codes.

**Comment by Senwang98** [comment]
@haoyuc 
Thank you for your understanding!
