### ISSUE TITLE
About pre-trained model

### ISSUE THREAD

**Issue by jjlinghu** [haoyuc/A2N#10]
Thank you for your amazing work!
I would like to know if the pre-trained model is provided?  I can't find it , sry.
And I notice that the methods of reconstruction module and Upsample module are nearest-neighbor interpolation and bilinear interpolation, respectively.Have you tried using sub-pixel related methods? And how is the result?
Thanks again.

**Comment by haoyuc** [comment]
Hi, our pre-trained models are [here: code/experiment/model/aan_x4.pt](https://github.com/haoyuc/A2N/blob/main/code/experiment/model/aan_x4.pt).

We have not tried sub-pixel related methods, it will bring more parameters, I guess it might have slightly better results.

**Comment by jjlinghu** [comment]
> Hi, our pre-trained models are [here: code/experiment/model/aan_x4.pt](https://github.com/haoyuc/A2N/blob/main/code/experiment/model/aan_x4.pt).
> 
> We have not tried sub-pixel related methods, it will bring more parameters, I guess it might have slightly better results.

Thanks a lot! Good luck for you.
