### ISSUE TITLE
Mismatch in the model architecture implementation and the one given in the paper

### ISSUE THREAD

**Issue by Anuj040** [haoyuc/A2N#2]
Thanks a lot for an interesting work on super-resolution and an easy to understand repository.
I am working to implement this repo in tensorflow ([link](https://github.com/Anuj040/superres/tree/master/A2N)). I noticed that the following skip connection is not shown in the Figure 3. of https://arxiv.org/abs/2104.09497.
Just wanted to confirm that.
https://github.com/haoyuc/A2N/blob/a04e78a3f3735553c4514521dd5b6937eee40aae/code/model/aan.py#L152

Thanks a lot for your time.
PS: If you feel my implementation worthy of reference, please consider that. Would be immensely grateful.

**Comment by haoyuc** [comment]
Thank you for your attention to our work! 
The skip connection in aan.py is the correct one. 
Your implementation is really great, I will add your repo in ReadMe later.  😁

**Comment by Anuj040** [comment]
Understood.
Thanks! Greatly appreciated.
